packageExtensions:
  "@essex/webpack-config@*":
    peerDependencies:
      typescript: "*"
      worker-loader: "*"
  "@thematic/fluent@*":
    peerDependencies:
      "@uifabric/icons": "*"
  gatsby@*:
    dependencies:
      "@babel/types": ^7.12.0
      babel-plugin-styled-components: ^1.11.1
  react-shadow@*:
    peerDependencies:
      styled-components: "*"
  styled-components@*:
    dependencies:
      react-is: ^16

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
